### ISSUE TITLE
Fails to compile on OS X 10.9 (missing <tr1/tuple>)

### ISSUE THREAD

**Issue by Steelskin** [google/open-vcdiff#41]
Original [issue 41](https://code.google.com/p/open-vcdiff/issues/detail?id=41) created by Jens.Alfke on 2013-10-27T04:00:35.000Z:

<b>What steps will reproduce the problem?</b>
1. Install OS X 10.9 and Xcode 5.0.1
2. Download and unpack open-vcdiff 0.8.3 tar ball
3. ./configure
4. make

<b>What is the expected output? What do you see instead?</b>

...
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I./src -I./src -I./src/zlib -I./gflags/src -I./gtest -I./gtest/include -DNDEBUG -DNO_THREADS -Wall -Wwrite-strings -Woverloaded-virtual -W -g -O2 -MT gtest.lo -MD -MP -MF .deps/gtest.Tpo -c gtest/src/gtest.cc  -fno-common -DPIC -o .libs/gtest.o
In file included from gtest/src/gtest.cc:34:
In file included from ./gtest/include/gtest/gtest.h:55:
In file included from ./gtest/include/gtest/internal/gtest-internal.h:40:
./gtest/include/gtest/internal/gtest-port.h:433:10: fatal error: 'tr1/tuple' file not found
# include &lt;tr1/tuple&gt;

```
     ^
```

1 error generated.
make: **\* [gtest.lo] Error 1

<b>What version of the product are you using? On what operating system?</b>

open-vcdiff 0.8.3
Mac OS X 10.9
Xcode 5.0.1

This is the first time I've tried to build this, so I don't know whether 0.8.3 would build on an earlier OS X. (But the home page says it's compatible, so I imagine 0.8.3 must've been tested on 10.8?)
